### ISSUE TITLE
Синтаксический анализатор сообщает об ошибке на корректных программах

### ISSUE THREAD

**Issue by kajigor** [Atos1337/FormalLanguages#1]
Программы приложены 

[t05.txt](https://github.com/Atos1337/FormalLanguages/files/5333706/t05.txt)
[t17.txt](https://github.com/Atos1337/FormalLanguages/files/5333707/t17.txt)

**Comment by Atos1337** [comment]
Fixed

**Comment by kajigor** [comment]
Напишите ответом на письмо, что вы исправили баг.
